### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by stephenajulu** [damnitrahul/gatsby-blog#1]
Hi, how are you?
This is absolutely beautiful.
Close to what i was looking for.
Could you kindly add Multi Author Support(with author pages), a newsletter and if possible could you kindly add a "Related Posts" under posts with a feature image?
or show me how to go about it.

**Comment by stephenajulu** [comment]
Also is it possible to keep the design going down.
I mean the cols. Instead of cols then list, the homepage just shows the latest posts in cols style?

**Comment by stephenajulu** [comment]
kindly help me, how can i make the featured design all the way down and still have space for ads?

**Comment by damnitrahul** [comment]
Hey, Custom layout is not supported as of now with this theme. Please feel free to fork it and customize it according to your need! 

You can achieve your desired layout by using a CSS grid and customizing the `blog-posts.js` and `blog-post-card.js`.
